# Model Training

### 1.1 Import Data and Required Packages
#### Importing Pandas, Numpy, Matplotlib, Seaborn and Warings Library.

In [2]:
#basic imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#modelling
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix, make_scorer, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.naive_bayes import GaussianNB

In [3]:
import warnings
warnings.filterwarnings('ignore')

#### Import the CSV Data as Pandas DataFrame

In [4]:
df = pd.read_csv('../notebooks/data/ai4i2020.csv')

#### show top 5 rows

In [5]:
df.head()

   UDI Product ID Type  Air temperature [K]  ...  HDF  PWF  OSF  RNF
0    1     M14860    M                298.1  ...    0    0    0    0
1    2     L47181    L                298.2  ...    0    0    0    0
2    3     L47182    L                298.1  ...    0    0    0    0
3    4     L47183    L                298.2  ...    0    0    0    0
4    5     L47184    L                298.2  ...    0    0    0    0

[5 rows x 14 columns]

#### Dropping unwanted columns

In [10]:
df = df.drop(columns=['UDI', 'Product ID'])

In [11]:
df.head()

  Type  Air temperature [K]  Process temperature [K]  ...  PWF  OSF  RNF
0    M                298.1                    308.6  ...    0    0    0
1    L                298.2                    308.7  ...    0    0    0
2    L                298.1                    308.5  ...    0    0    0
3    L                298.2                    308.6  ...    0    0    0
4    L                298.2                    308.7  ...    0    0    0

[5 rows x 12 columns]

#### preparing X and Y variables

In [12]:
df.columns

Index(['Type', 'Air temperature [K]', 'Process temperature [K]',
       'Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]',
       'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF'],
      dtype='str')

In [14]:
X = df[['Type', 'Air temperature [K]', 'Process temperature [K]','Rotational speed [rpm]', 'Torque [Nm]', 'Tool wear [min]']]

In [18]:
print(f"Categories in Type : {df['Type'].unique()}")

Categories in Type : <ArrowStringArray>
['M', 'L', 'H']
Length: 3, dtype: str

In [19]:
y = df['Machine failure']

In [20]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Machine failure, dtype: int64

In [21]:
# Create Column Transformer with 3 types of transformers
num_features = X.select_dtypes(include='number').columns
cat_features = X.select_dtypes(exclude='number').columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoding", oh_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features)
    ]
)

In [22]:
X = preprocessor.fit_transform(X)

In [23]:
X.shape

(10000, 8)

In [26]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape

((8000, 8), (2000, 8))